### ISSUE TITLE
[BUG]  File upload button is not visible in the document upload page

### ISSUE THREAD

**Issue by jrosetf** [WuriGuinea/wuriguinea-pre-registration#4]
File upload button is not visible in the document upload page

1. Login to pre registration
2. Fill in demographics and navigate to document upload screen
3. Upload button is not visible

**Expected behavior**
Upload button should be clearly visible

**Screenshots**

![image](https://user-images.githubusercontent.com/45810590/91039724-b3eead80-e62a-11ea-9220-7a6c313d2e4c.png)

**Comment by wuritechteam** [comment]
@mombe090  and @ankitvaishnav to fix NgX server setting

**Comment by tisshadjac** [comment]
@mombe090 to follow up with MOSIP team

**Comment by mombe090** [comment]
PR create to address issue https://github.com/WuriGuinea/mosip-guinea-ref-impl/pull/263

**Comment by wuritechteam** [comment]
@mombe090 , ETA = Thu. 29 Oct

**Comment by mombe090** [comment]
Issue solved, bellow the screenShot

<img width="1254" alt="Screen Shot 2020-10-28 at 13 36 22" src="https://user-images.githubusercontent.com/14869997/97446487-604c5900-1926-11eb-885a-fb2d03ed49dd.png">
